# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xloka
email: a.saleh.ismael@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full-stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xloka.github.io" # the base hostname & protocol for your site
twitter_username: mrxloka
github_username:  Xloka
facebook_url:  "https://www.facebook.com/xlokacom"
tumblr_url:  "http://xloka.hackforward.ninja/"
profileimg: "/img/xloka-profile.jpg"
# Build settings
markdown: kramdown
